# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d55588d46d99cd84356caa256a9ee9c8890a88c9eeba349a0181e6afb6c49d1f7ab59f486c9f808e34c6e5adb88e0d13887757cdef2d8a3d09de14500b6f103

test:
  secret_key_base: 84d6f738cb4b3451b7802b09498bb8400c09b93d24bacc813b2b946cc52d584c5b0d7d9d57009b87e50274eb3c9a202f8f38a28e9b955f16b9e276a12eac1c60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
